name: Create Release
run-name: Create Release

on:
  push:
    branches:
      - master

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      
      - name: Get XML
        id: get_xml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'shippify/config.xml'
          xpath: '//version'

      - name: Zip Module
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: 'shippify'
          filename: 'shippify.zip'

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: 'shippify.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_xml.outputs.info }}
